/* tslint:disable */
/* eslint-disable */
/**
 * Tallii Platform
 * Platform Service for tallii.io
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: adam.aho@hey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from '../runtime';
import {
  LoginSignupResponseModelUser,
  LoginSignupResponseModelUserFromJSON,
  LoginSignupResponseModelUserFromJSONTyped,
  LoginSignupResponseModelUserToJSON,
} from './LoginSignupResponseModelUser';

/**
 *
 * @export
 * @interface LoginSignupResponseModel
 */
export interface LoginSignupResponseModel {
  /**
   *
   * @type {string}
   * @memberof LoginSignupResponseModel
   */
  accessToken?: string;
  /**
   *
   * @type {LoginSignupResponseModelUser}
   * @memberof LoginSignupResponseModel
   */
  user?: LoginSignupResponseModelUser;
}

export function LoginSignupResponseModelFromJSON(json: any): LoginSignupResponseModel {
  return LoginSignupResponseModelFromJSONTyped(json, false);
}

export function LoginSignupResponseModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LoginSignupResponseModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    accessToken: !exists(json, 'access_token') ? undefined : json['access_token'],
    user: !exists(json, 'user') ? undefined : LoginSignupResponseModelUserFromJSON(json['user']),
  };
}

export function LoginSignupResponseModelToJSON(value?: LoginSignupResponseModel | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    access_token: value.accessToken,
    user: LoginSignupResponseModelUserToJSON(value.user),
  };
}
