/* tslint:disable */
/* eslint-disable */
/**
 * Tallii Platform
 * Platform Service for tallii.io
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: adam.aho@hey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from '../runtime';
import {
  UserInfoModel,
  UserInfoModelFromJSON,
  UserInfoModelFromJSONTyped,
  UserInfoModelToJSON,
} from './UserInfoModel';

/**
 *
 * @export
 * @interface LoginSignupResponseModelUser
 */
export interface LoginSignupResponseModelUser {
  /**
   *
   * @type {UserInfoModel}
   * @memberof LoginSignupResponseModelUser
   */
  schema?: UserInfoModel;
}

export function LoginSignupResponseModelUserFromJSON(json: any): LoginSignupResponseModelUser {
  return LoginSignupResponseModelUserFromJSONTyped(json, false);
}

export function LoginSignupResponseModelUserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LoginSignupResponseModelUser {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    schema: !exists(json, 'schema') ? undefined : UserInfoModelFromJSON(json['schema']),
  };
}

export function LoginSignupResponseModelUserToJSON(
  value?: LoginSignupResponseModelUser | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    schema: UserInfoModelToJSON(value.schema),
  };
}
