/* tslint:disable */
/* eslint-disable */
/**
 * Tallii Platform
 * Platform Service for tallii.io
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: adam.aho@hey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from '../runtime';
/**
 *
 * @export
 * @interface LoginRequestModel
 */
export interface LoginRequestModel {
  /**
   *
   * @type {string}
   * @memberof LoginRequestModel
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof LoginRequestModel
   */
  password: string;
}

export function LoginRequestModelFromJSON(json: any): LoginRequestModel {
  return LoginRequestModelFromJSONTyped(json, false);
}

export function LoginRequestModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LoginRequestModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
  };
}

export function LoginRequestModelToJSON(value?: LoginRequestModel | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    password: value.password,
  };
}
