/* tslint:disable */
/* eslint-disable */
/**
 * Tallii Platform
 * Platform Service for tallii.io
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: adam.aho@hey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from '../runtime';
import {UserModel, UserModelFromJSON, UserModelFromJSONTyped, UserModelToJSON} from './UserModel';

/**
 *
 * @export
 * @interface LoginSignupResponseModel
 */
export interface LoginSignupResponseModel {
  /**
   *
   * @type {string}
   * @memberof LoginSignupResponseModel
   */
  accessToken: string;
  /**
   *
   * @type {UserModel}
   * @memberof LoginSignupResponseModel
   */
  user: UserModel;
}

export function LoginSignupResponseModelFromJSON(json: any): LoginSignupResponseModel {
  return LoginSignupResponseModelFromJSONTyped(json, false);
}

export function LoginSignupResponseModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LoginSignupResponseModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    accessToken: json['access_token'],
    user: json['user'],
  };
}

export function LoginSignupResponseModelToJSON(value?: LoginSignupResponseModel | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    access_token: value.accessToken,
    user: value.user,
  };
}
