/* tslint:disable */
/* eslint-disable */
/**
 * Tallii Platform
 * Platform Service for tallii.io
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: adam.aho@hey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from '../runtime';
import {TeamModel, TeamModelFromJSON, TeamModelFromJSONTyped, TeamModelToJSON} from './TeamModel';
import {UserModel, UserModelFromJSON, UserModelFromJSONTyped, UserModelToJSON} from './UserModel';

/**
 *
 * @export
 * @interface ScoreboardModel
 */
export interface ScoreboardModel {
  /**
   *
   * @type {number}
   * @memberof ScoreboardModel
   */
  scoreboardId: number;
  /**
   *
   * @type {string}
   * @memberof ScoreboardModel
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ScoreboardModel
   */
  game: string;
  /**
   *
   * @type {UserModel}
   * @memberof ScoreboardModel
   */
  createdBy: UserModel;
  /**
   *
   * @type {Date}
   * @memberof ScoreboardModel
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof ScoreboardModel
   */
  updatedAt: Date;
  /**
   *
   * @type {Array<TeamModel>}
   * @memberof ScoreboardModel
   */
  teams: Array<TeamModel>;
}

export function ScoreboardModelFromJSON(json: any): ScoreboardModel {
  return ScoreboardModelFromJSONTyped(json, false);
}

export function ScoreboardModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ScoreboardModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    scoreboardId: json['scoreboard_id'],
    name: json['name'],
    game: json['game'],
    createdBy: UserModelFromJSON(json['created_by']),
    createdAt: new Date(json['created_at']),
    updatedAt: new Date(json['updated_at']),
    teams: (json['teams'] as Array<any>).map(TeamModelFromJSON),
  };
}

export function ScoreboardModelToJSON(value?: ScoreboardModel | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    scoreboard_id: value.scoreboardId,
    name: value.name,
    game: value.game,
    created_by: UserModelToJSON(value.createdBy),
    created_at: value.createdAt.toISOString(),
    updated_at: value.updatedAt.toISOString(),
    teams: (value.teams as Array<any>).map(TeamModelToJSON),
  };
}
