/* tslint:disable */
/* eslint-disable */
/**
 * Tallii Platform
 * Platform Service for tallii.io
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: adam.aho@hey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from '../runtime';
/**
 *
 * @export
 * @interface SignupRequestModel
 */
export interface SignupRequestModel {
  /**
   *
   * @type {string}
   * @memberof SignupRequestModel
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof SignupRequestModel
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof SignupRequestModel
   */
  password: string;
}

export function SignupRequestModelFromJSON(json: any): SignupRequestModel {
  return SignupRequestModelFromJSONTyped(json, false);
}

export function SignupRequestModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SignupRequestModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    username: json['username'],
    password: json['password'],
  };
}

export function SignupRequestModelToJSON(value?: SignupRequestModel | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    username: value.username,
    password: value.password,
  };
}
