/* tslint:disable */
/* eslint-disable */
/**
 * Tallii Platform
 * Platform Service for tallii.io
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: adam.aho@hey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from '../runtime';
/**
 *
 * @export
 * @interface UpdateUserRequestModel
 */
export interface UpdateUserRequestModel {
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequestModel
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequestModel
   */
  avatarBackground: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequestModel
   */
  avatarEmoji: string;
}

export function UpdateUserRequestModelFromJSON(json: any): UpdateUserRequestModel {
  return UpdateUserRequestModelFromJSONTyped(json, false);
}

export function UpdateUserRequestModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateUserRequestModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    username: json['username'],
    avatarBackground: json['avatar_background'],
    avatarEmoji: json['avatar_emoji'],
  };
}

export function UpdateUserRequestModelToJSON(value?: UpdateUserRequestModel | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    username: value.username,
    avatar_background: value.avatarBackground,
    avatar_emoji: value.avatarEmoji,
  };
}
