/* tslint:disable */
/* eslint-disable */
/**
 * Tallii Platform
 * Platform Service for tallii.io
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: adam.aho@hey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from '../runtime';
/**
 *
 * @export
 * @interface UserModel
 */
export interface UserModel {
  /**
   *
   * @type {number}
   * @memberof UserModel
   */
  userId: number;
  /**
   *
   * @type {string}
   * @memberof UserModel
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof UserModel
   */
  email: string;
  /**
   *
   * @type {Date}
   * @memberof UserModel
   */
  createdAt: Date;
}

export function UserModelFromJSON(json: any): UserModel {
  return UserModelFromJSONTyped(json, false);
}

export function UserModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userId: json['user_id'],
    username: json['username'],
    email: json['email'],
    createdAt: new Date(json['created_at']),
  };
}

export function UserModelToJSON(value?: UserModel | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user_id: value.userId,
    username: value.username,
    email: value.email,
    created_at: value.createdAt.toISOString(),
  };
}
