/* tslint:disable */
/* eslint-disable */
/**
 * Tallii Platform
 * Platform Service for tallii.io
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: adam.aho@hey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from '../runtime';
/**
 *
 * @export
 * @interface UserInfoModel
 */
export interface UserInfoModel {
  /**
   *
   * @type {number}
   * @memberof UserInfoModel
   */
  userId?: number;
  /**
   *
   * @type {string}
   * @memberof UserInfoModel
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof UserInfoModel
   */
  email?: string;
  /**
   *
   * @type {Date}
   * @memberof UserInfoModel
   */
  createdAt?: Date;
}

export function UserInfoModelFromJSON(json: any): UserInfoModel {
  return UserInfoModelFromJSONTyped(json, false);
}

export function UserInfoModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfoModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userId: !exists(json, 'user_id') ? undefined : json['user_id'],
    username: !exists(json, 'username') ? undefined : json['username'],
    email: !exists(json, 'email') ? undefined : json['email'],
    createdAt: !exists(json, 'created_at') ? undefined : new Date(json['created_at']),
  };
}

export function UserInfoModelToJSON(value?: UserInfoModel | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user_id: value.userId,
    username: value.username,
    email: value.email,
    created_at: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
  };
}
